JuliaIO/JSON.jl

- .travis.yml
- src/JSON.jl
- src/Parser.jl
Since I broke #102, I felt like I should do the rebase, so here it is.
> rebased deprecation fixes

- REQUIRE
- src/JSON.jl
- test/runtests.jl
There aren't that many, and it seems they're pretty easily fixed.
> Fix Julia v0.5 deprecations

- appveyor.yml
Also run tests on supported release versions of Julia
Use Pkg.test("JSON") which now handles adding DataStructures in test/REQUIRE
> Modernize AppVeyor

- test/json-checker.jl
> Make it more obvious that allowed failures are allowed

- REQUIRE
- src/JSON.jl
- test/runtests.jl
The first commit fixes #152 and adds tests.
The second commit is unrelated, but since it is a change in the same function, I have included it in this PR.
cc @xqrongm
> Fix #152, fix deprecation warning

- .travis.yml
- appveyor.yml
Adds v0.5 to the Travis and Appveyor build matrices.
cc @tkelman Does this look right?
> Add v0.5 to Travis and Appveyor

- README.md
Uses JuliaIO links instead of JuliaLang ones.
> Update links on README

- REQUIRE
- test/runtests.jl
Also bumps Compat dependency to <s>0.8.5</s> 0.9.5.
> Fix test deprecation warning on 0.6

- src/JSON.jl
- src/bytes.jl
- src/specialized.jl
- test/lowering.jl
- test/runtests.jl
These two commits repair the tests on Julia v0.6.
> Fix tests on 0.6

- REQUIRE
- src/Parser.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
> Fix 0.6 abstract type declaration depwarn

- src/JSON.jl
- src/Parser.jl
- test/lowering.jl
- test/runtests.jl
This deletes several (unexported, internal) things that are not needed and adds some tests to get to 100% test coverage.
> Add missing test coverage and remove unneeded internal code

- .travis.yml
- REQUIRE
- appveyor.yml
- src/Parser.jl
- src/Writer.jl
- src/specialized.jl
- test/lowering.jl
- test/runtests.jl
- test/serializer.jl
This PR drops 0.4 support. I don't know if it's the best time to do so; feedback is welcome.
> Drop v0.4 support

- src/Writer.jl
- test/REQUIRE
- test/runtests.jl
- test/standard-serializer.jl
Needed for https://github.com/JuliaPlots/Plots.jl/pull/1067.
> Fix writing arrays with unconventional indices

- REQUIRE
- src/Parser.jl
- test/lowering.jl
- test/runtests.jl
- test/serializer.jl
Fix some deprecations on 0.7 for things that moved to the standard library.
Will merge this tomorrow if there aren't any objections.
> Revisions for standard library

- REQUIRE
- src/Parser.jl
- src/Writer.jl
- test/standard-serializer.jl
cc @ararslan, @nalimilan 
ref https://github.com/JuliaLang/julia/pull/23642#issuecomment-348326150
> Use Nullables

- README.md
Took me a few minutes reading code to figure out how to do this
> Document indentation argument on the front page

- src/Parser.jl
- src/Writer.jl
- src/specialized.jl
- test/json-checker.jl
- test/lowering.jl
- test/runtests.jl
Special-cased Symbol for one of them, which felt icky but works.
> Fix all existing deprecation warnings

- src/Serializations.jl
- src/Writer.jl
cc @ararslan 
The v0.6 test failure will need a Compat change, coming soon.
> Update for fieldnames change in v0.7

- .travis.yml
- appveyor.yml
- src/Writer.jl
```
julia> struct SingletonType end
julia> a = SingletonType()
SingletonType()
julia> nfields(typeof(SingletonType()))
20
```
> nfields should be used on objects not types

- src/Writer.jl
https://github.com/JuliaIO/JSON.jl/issues/256
> Add support for missing

- README.md
- Removes some obsolete (and broken) badges
- Replace `Pkg.add` instruction with 1.0+ `pkg>` instruction
- Use headings more appropriately
Closes #271
> Revise README leading paragraphs

- README.md
Closes #298.
There are other examples of serializations in the tests, but they are a little messy, so I've chosen not to link to them from this README. When/if we migrate to a proper documentation system, we can include more examples.
> Document serialization

- README.md
> See alternative package JSON3
