JuliaIO/JSON.jl

src/JSON.jl, test/runtests.jl
Fixes this on Julia 0.4:
````
julia> type t
i::Int
end
julia> JSON.print(IOBuffer(), t(1))
ERROR: type DataType has no field names
in _print at /home/tan/.julia/v0.4/JSON/src/JSON.jl:141
in print at /home/tan/.julia/v0.4/JSON/src/JSON.jl:191 (repeats 2 times)
````
=> use @compat fieldnames instead of typeof(x).names

src/Parser.jl
This package used two undocumented, unexported functions from `base/utf16.jl`.
This removes that dependency, which broke things when those functions were renamed.
=> Eliminate use of undocumented Base.utf16_* functions (Fix #110)

REQUIRE, src/JSON.jl
fixes #115 
`Compat.jl` should take care of the v0.3 compatibility.
=> fix mmap deprecation warning

src/Parser.jl, test/runtests.jl
After:
```
ERROR: LoadError: Unexpected char: _
Line: 0
Around: ...["🍕"_"🍕"...
^
```
Before:
```
ERROR: LoadError: UnicodeError: invalid character index
in next at ./unicode/utf8.jl:65
```
=> Fix #99 by correctly iterating through string

src/JSON.jl
Passed `Pkg.test` on 0.4. Needed to resolve dependencies during precompilation.
=> Add precompile directive

.travis.yml, src/Parser.jl
closes #123
first commit adds a test to demonstrate failure case on travis, then second commit moves the conditional dependency on DataStructures into an `__init__` function.
=> Fix loading of precompiled JSON when DataStructures is not present

README.md, src/JSON.jl, src/Parser.jl, test/runtests.jl
As discussed in #128, this provides more flexibility, and avoids the pseudo-dependency on DataStructures that has been causing precompilation problems.
=> change ordered keyword to dicttype keyword

test/runtests.jl
Ref JuliaLang/julia#13923
@amitmurthy
=> Fix usage of RemoteRef

src/JSON.jl, test/runtests.jl
Fixes #90 and https://github.com/johnmyleswhite/Vega.jl/issues/107
Vega.jl examples to show this works in the wild (i.e. parses `Date/DateTime` to a readable format that a JavaScript library will accept and in proper ordinal order)
=> Correct Date/DateTime

src/JSON.jl
The use of `colon` had nothing to do with `Base.colon`, so it isn’t appropriate to extend (and hence pun) it.
This is the same change as https://travis-ci.org/TotalVerb/JSON.jl/builds/136328207, which <s>passes Travis on my account</s> <s>is being built right now</s> passes Travis on my account. I put [ci skip] on this one because there's a fairly long Travis backlog. I can remove that if it's inappropriate.
=> Rename “colon” to “separator”

REQUIRE, test/runtests.jl
Having red text be printed every time `Pkg.test("JSON")` is run is getting tiresome. Compat has the new `is_windows()` function, and these macros are not coming back (https://github.com/JuliaLang/julia/pull/16658).
Also bumped the Compat version to what is appropriate. With this and #140, there is no more red output for tests on release or master.
Closes #146
=> Fix @os_only deprecation warnings

bench/micro.jl
These are the benchmarks that identified some major regressions in #151 (which have since been fixed). I'm pretty sure this file only works on v0.5, but I hope that's OK because as long as the package works on v0.3 and v0.4, I don't think it's critical to actively profile its performance.
=> Add set of serialization microbenchmarks

README.md, src/JSON.jl, test/lowering.jl, test/runtests.jl
Implements the idea in #150. The following is a quick recap (redundant with #150) of why this is needed:
Lots of packages currently overload `JSON._print` to define custom JSON serialization. This is really bad, because:
- Packages need to reimplement a lot of serialization code, like how to serialize dicts and arrays.
- Overloads of JSON._print can write anything — including stuff that isn't JSON. This isn't good.
- Packages tend to depend on implementation details, like what the name of JSON.separator is.
- Packages work independently of the existing parser system, so they do not benefit from updates to serialization code here.
This PR implements:
- Introduce JSON.lower, designed to be overloaded, that converts an object to another "primitive" object that JSON can serialize (Dict, …
=> Add JSON.lower for a better serialization API

test/runtests.jl
As pointed out by @vtjnash, this wasn't doing anything. It also was only used in this particular test.
=> Remove usage of `line_buffered`

src/JSON.jl, test/runtests.jl
Fixes #163 
I'm not super familiar with how the JSON serialization is expected to work, particularly how strict it's supposed to be with round-tripping floating-point numbers. LMK if just converting to a Float64 for JSON serialization is a bad idea.
Related:
JuliaLang/julia#17720
JuliaLang/julia#18053
JuliaLang/julia#18682
spencerlyon2/PlotlyJS.jl#78
=> adds test and workaround for 0.5 issue with printing Float32s

src/JSON.jl, test/runtests.jl
Added `_writejson` method for `Nullable` values. Maps to JSON `null` if
value is null.
(edit by TotalVerb: fixes #132)
=> Support for `Nullable`

src/JSON.jl, test/REQUIRE, test/lowering.jl, test/runtests.jl
My main use case for this is so that PlotlyJS.jl is able to plot
my vectors of fixed-point numbers, which come up a lot when loading
audio files.
=> adds lowering fallback for Real subtypes that converts to Float64

src/Common.jl, src/JSON.jl, src/Parser.jl, src/bytes.jl, src/errors.jl
Split off #162 to make it easier to review.
No functional change. Just a merge of the two places where we have defined constants for bytes. Will merge tomorrow or later this week if CI passes and there are no objections.
=> Factor bytes and errors into Common submodule

src/JSON.jl, src/Parser.jl, src/specialized.jl
In addition to removing some `string.data` constructs that will break after JuliaLang/julia#19449, I also removed a little pre-0.4 code (now obsolete since we REQUIRE 0.4).
=> compatibility for JuliaLang/julia#19449

src/JSON.jl
Fixes a deprecation warning on 0.6
=> Change typealias to const assignment

src/JSON.jl, src/Serializations.jl, test/runtests.jl, test/serializer.jl
This fixes the major issues with overriding the old `_writejson` (née `_print`):
- Overloads of show_json are easily constrained to writing valid JSON. Backdoors are available for performance reasons, but situations where invalid JSON can be written are easily caught and fixed.
- Packages that overloaded `_print` tended to use low-level implementation details, such as `JSON.separator`. These packages broke when the low-level implementation changed. This proposal  will introduce high-level constructs with a stable, documented API.
- Upgrades to serialization performance, or bugfixes, are automatically available to packages overriding `show_json`.
- Extensions to the formats available to serialize `JSON` in can be considered in the future, and packages overloading `show_json` will correctly …
=> RFC: Introduce StructuralContext and Serialization for finer-grained serialization control

README.md
`JSON._print` has been gone since 0.6.0, so we should remove its mention in the README.md.
=> Remove mention of `_print` from README

REQUIRE, src/specialized.jl
This avoids extra allocation and copying for the in-memory string
parsing.
Fixes #197.
(As far as I can tell, the other uses of `Vector{UInt8}` are not passed to the `String` constructor, so do not require this change.)
=> Use StringVector instead of Vector{UInt8}

src/Writer.jl, test/lowering.jl, test/runtests.jl
Fixes #201. I made some unrelated changes also:
- The `JSONPrimitive` constant is not used anywhere and so I've deleted it.
- To avoid excess allocations in lowering `Char` and `Type`, they're now lowered to themselves and printed directly by the string-like `show_json` (previously, we were doing that only for symbols and strings). The same treatment applies to `Enum`; users can still define `lower` to customize the printing if necessary (see test/lowering.jl). We can do this with dates too, but that's easier to do once 0.4 support is dropped.
=> Support Enums

src/Writer.jl, test/serializer.jl
Currently, 0-dimensional arrays are not properly handled by the generic `_writejson()`.
The proposed specialized method just writes the first (and only) element.
=> support 0-dim arrays

src/Writer.jl, test/standard-serializer.jl
Fix #196.
This has been requested for a while and makes sense to do. The first commit is unrelated but just a simplification to the code with no functional change.
@oyd11, please review and confirm that this addresses your use case.
=> Lower `AbstractSet` through `collect`

src/Writer.jl, test/standard-serializer.jl
@quinnj, @kmsquire please review if you have the time. I implemented this as `show_json` instead of `lower` because allocating `Dict`s is expensive...
Close #106.
=> Support Pair, serializing as an object

bench/micro.jl, src/Parser.jl, src/Serializations.jl, src/Writer.jl, test/lowering.jl, test/regression/issue109.jl, test/serializer.jl
Since benchmarks are not a part of JSON itself, I didn't bother trying to support both 0.5 and 0.6 on them; this PR makes 0.6 is required to run the benchmarks.
This is a really ugly PR but luckily only a temporary solution until we can drop support for 0.5.
=> Fix the deprecation warnings

src/Writer.jl
This allows reusing `CompositeTypeWrapper` for defining custom `lower()` methods that exclude certain fields from serialization.
=> show_json(CompTypeWrapper): access fields by name

REQUIRE, bench/bench.jl, src/Common.jl, src/Parser.jl, src/Serializations.jl, src/Writer.jl, test/json-checker.jl, test/json-samples.jl, test/lowering.jl, test/parser/parsefile.jl, test/regression/issue109.jl, test/serializer.jl
Fixes the test failure on nightly, and more deprecations. Some deprecations can't be easily fixed right now.
=> Unescape solidus in tests, and other deprecations

.travis.yml, REQUIRE, appveyor.yml, src/Common.jl, src/JSON.jl, src/Parser.jl, src/Serializations.jl, src/Writer.jl, src/bytes.jl, src/specialized.jl, test/REQUIRE, test/lowering.jl, test/regression/issue109.jl, test/serializer.jl
This drops the 0.5 support for JSON, and along with it several hacks and Compats we've been using. Compat is still needed for tests. Also has the effect of fixing all the deprecations on master.
Will merge and tag in a few days if there are no objections.
=> Drop v0.5 support, Compat dependency

REQUIRE, src/Parser.jl
cc @tkelman 
Sorry for the oversight. This partially reverts the removal of the Compat dependency in 0.15.0. Should be tagged as 0.15.1 when merged.
(as an aside: for these reasons, I suppose it's best for tests to avoid importing Compat when the main library doesn't, to avoid these situations being missed.)
=> Revert Compat dependency removal

src/Writer.jl, test/parser/invalid-input.jl
Remove an obsolete branch and add an expected error case for invalid input, to get back to 100% test coverage.
=> Restore 100% test coverage

bench/bench.jl
This fixes a deprecation warning for `tic()` and `toq()` in the benchmark script.
=> Fix benchmark deprecation warning

README.md, src/Parser.jl, test/parser/inttype.jl, test/runtests.jl
* Added a ParserContext object, containing the `DictType` and `IntType` to use for parsing JSON
This is a minimally invasive way of giving the user more control over parsing.  
A possible extension would be to allow specifying the float format to parse (e.g., `DecFP`, `Decimals`, `FixedPointNumbers`, etc.), although this would probably require a bit more work.
**Edit:** Addresses part of #223, although it does not implement overflow checking.
=> Allow user to specify integer parsing type (fixes #223)

REQUIRE, src/Writer.jl, test/REQUIRE, test/lowering.jl, test/runtests.jl
Fix to [225](https://github.com/JuliaIO/JSON.jl/issues/225)
=> Address breaking change on nightly

src/Common.jl, src/Writer.jl, src/bytes.jl
Ref https://github.com/JuliaLang/julia/pull/25021. Needed for Nanosoldier.
=> Fix for Base Unicode functions moving to stdlib

REQUIRE, src/Parser.jl, src/specialized.jl
This eliminates a number of unnecessary string and buffer allocations.   It eliminates those from #234, and also eliminates several associated with Unicode escapes: rather than converting a `Char` to a `String` to get the UTF-8 representation, I write it directly to a buffer.
Most of the changes are deleting/simplifying code: my favorite kind of optimization :wink:.
=> reduce number of string/buffer allocations

README.md, src/JSON.jl, src/Writer.jl, test/serializer.jl
This exports a `JSONText(s::String)` object that you can use to embed raw JSON in directly in the output.
For example, this would be useful in IJulia for JuliaLang/IJulia.jl#621
=> JSONText(string) for embedding raw JSON in the output

src/specialized.jl
=> Handle IOBuffer signatures on 0.6 and 0.7

.travis.yml, appveyor.yml, src/Parser.jl
Commit 1 works around the slow dynamic dispatch that currently exist in Base (https://github.com/JuliaLang/julia/issues/29887). This significantly reduces the overhead of creating the Parser:
Before:
```jl
julia> @btime JSON.parse("\"foo\"")
3.080 μs (2 allocations: 64 bytes)
"foo"
```
After:
```jl
julia> @btime JSON.parse("\"foo\"")
196.499 ns (3 allocations: 160 bytes)
"foo"
```
Note that quite a lot of JSON can be parsed within 3μs.
Commit 2, caches the UInt8 vector which is filled with bytes of digits. Reusing the same vector has a bunch of benefits in terms of not having to grow it over and over and the data will be hot.
Using the benchmark
```jl
julia> using Random
julia> a = string("[", join([rand(Int) for i in 1:10^3], ","), "]");
```
Before:
```jl
julia> @btime JSON.parse($a) …
```
=> A few performance improvements

src/Writer.jl, test/standard-serializer.jl
Fixes the `BoundsError: attempt to access 256-element Array{Array{UInt8,1},1} at index [0]` error that occurs when serializing a string containing the byte `0xff`.
=> Fix indexing of ESCAPED_ARRAY

src/Parser.jl, src/bytes.jl, src/specialized.jl, test/parser/nan-inf.jl, test/runtests.jl
* Allows reading out-of-spec JSON files which include `Nan`, `Infinity`, and `-Infinity`
The ideal solution to reading out-of-spec JSON files was proposed by @TotalVerb in #169.
Until that is implemented, this provides a pragmatic solution for people to read these types of JSON files when they don't have control over the file generation.
=> RFC: Add `allownan` keyword argument to parse() (Fixes #168)

src/Parser.jl, test/parser/null.jl, test/runtests.jl
Currently both `nothing` and `missing` are written to JSON files as `null`, but parsing such files results in `nothing`. Now the user can pass a `null=` keyword argument to `parse` and `parsefile` to specify the Julia value that results from parsing JSON's `null`.
=> Allow specifying a value to use when parsing null

src/Writer.jl, test/lowering.jl
This lets `show_json(..., ::CompositeTypeWrapper)` potentially do more interesting things by providing a custom `getproperty` method.
~It also has `show_json` apply `something` to values of type `Some`.~ I decided it would be safer not to assume this is always the desired behavior.
=> Made `show_json` for composite types more flexible via `propertynames`/`getproperty`.

src/Writer.jl
As shown in #279, JSON.json(NamedTuple()) failed.
This is because lower(NamedTuple()) fails (because nfields(NamedTuple()) is 0).
So, I changed show_json(NamedTuple()) not to call lower().
fixes #279
=> Fix show_json to serialize empty NamedTuple

README.md
Partially address #298 (still need docs for `Serialization`, but I only had time to write these so far).
I apologize for the lack of documentation when I implemented these features — it had been on my TODO list but slipped from the mind. I will make another PR with docs and examples for `Serialization` soon.
=> Add documentation for StructuralContext to README

Project.toml
JSON.jl currently has an unbounded dependency - this PR sets the compatibility range to `[0.0.0 - 2.0.0)`, which includes all versions currently supported, but sets an upper bound at `v2.0.0`.
(I'm only creating this minor PR because [JSON.jl has so many dependents](https://www.juliahub.com/ui/Packages/JSON/uf6oy/0.21.0?t=2).)
=> Compat entry for Parsers

Project.toml
This allows us to get a new JSON version out to everyone with the latest bugfixes and improvements.
=> revert 1.0 bump and tag + release 0.21.1 instead

Project.toml, src/Parser.jl, test/json-checker.jl
Update the Parsers compat versions to `"1, 2"`. As of v1.0.5,
`Parsers.tryparse` ensured the full input buffer was consumed when
parsing a value (as mentioned desirable in the now-deleted comment in
`float_from_bytes`). So dropping support for older Parsers versions
allows us to trust `Parsers.tryparse`, and those pre-1.0 versions are
pretty old at this point anyway.
I locally ran the JSON.jl tests under both Parsers v2.0.1 and v1.1.1 and
ensured both were passing, so it shouldn't matter which version of
Parsers ends up getting installed if there are other packages which
don't 2.0 yet.
=> Update Parsers support

src/JSON.jl
This tiny PR Improves the ttfx time of Blink.jl by 5 seconds. Probably also helps other packages that use JSON.jl
Current master here and with Blink.jl:
```julia
julia> @time using Blink
5.583824 seconds (17.56 M allocations: 740.126 MiB, 6.44% gc time, 88.95% compilation time)
julia> @time Window()
12.164188 seconds (28.92 M allocations: 1.293 GiB, 3.17% gc time, 98.19% compilation time)
Window(1, Electron(Process(`/home/raf/.julia/dev/Blink/deps/atom/electron /home/raf/.julia/dev/Blink/src/AtomShell/main.js port 3466`, ProcessRunning), Sockets.TCPSocket(RawFD(22) active, 0 bytes waiting), Dict{String, Any}("callback" => Blink.var"#1#2"())), Page(1, WebSocket(server, CONNECTED), Dict{String, Any}("webio" => Blink.AtomShell.var"#22#23"{Blink.AtomShell.WebIOBlinkComm}(Blink.AtomShell.WebIOB …
```
=> add basic precompilation

src/Parser.jl
This format is not supported since a long time.
Should we remap Associative to AbstractDict too ?
=> Update doc with correct parameterized function syntax

README.md
Fix outdated grammar in "Documentation" in README.md.
`Array{T, N}` is equivalent to `Array`.
=> Fix outdated grammar in "Documentation" in README.md

src/Writer.jl, test/runtests.jl
I noticed that writing can blow up when there are recusrive objects that reference each other.
(For example, in HTTP.jl, `Response` and `Request` reference each other)
This PR proposes a simple API for the `CompactContext` and `PrettyContext` where
`objectid` of objects will be tracked recursively when writing and it's configurable
what should be written out when a recursive cycle is detected.
Custom contexts can "hook in" to this behavior by subtyping `RecursiveCheckContext` and
including the required fields (see docs for new context). Otherwise, there shouldn't
be any functional change to APIs in any way.
cc: @vilterp (oops, wrong ping the 1st time)
=> Introduce a recursive cycle check when writing

.github/workflows/CI.yml
This will allow building docs for stable releases, which is useful for referring to specific versions. If you create a tag `v1.0.0+docs` on the merge commitof this PR it'll create the docs for v1.0.0.
=> Add `release` trigger for CI workflow

docs/src/writing.md, src/write.jl, test/json.jl
=> Add check for positive float precision for non-shortest float_style
